#Mis配置文件
#帅帅的凯凯~
#配置开始==================
#每个玩家进服的时候都会给一个，当拿着这个玩意右键的时候打开菜单主页，特殊值可以不限定，当特殊值为x时默认匹配所有，特殊值默认为0,当这个值为空(null{在Yml文件内用~表示})时不适用快捷工具！
快捷工具: '347:0'
#当这个值为真时，使用快捷工具将会打开商店主页而不是打开菜单主页
快捷打开为商店: false
货币单位: 金币
#是否开启个人商店
个人商店: true
#上架每个物品到个人商店的价格
上架耗资: 0
个人商店介绍修改费用: 1000